### ISSUE TITLE
The "Delete Output Folders" option is not deleting the bin and obj folders

### ISSUE THREAD

**Issue by HobDev** [mfractor/mfractor-feedback#171]
##Installation Information

```
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 19.2.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 3.9.3
Product Variant: Visual Studio Mac
Product Variant Version: 8.3.11.1
Product SKU: MFRACTOR-VS-MAC
Commit SHA: 8c50ab82483f36fc9fe8f61be2193401e9b4d396
Revision: 3980
Branch: master
Date: 11/12/2019 12:57:24 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment]
@HobDev What is your delete output folders configuration for the project/solution that is failing?

Please go to **MFractor** -> **Preferences** -> **Delete Output Folders**.

**Comment by HobDev** [comment]
bin and obj

**Comment by HobDev** [comment]
When I check all four options in the delete output folders configurartion it deletes the output folders. But when I choose bin and obj only it deletes the bin folder but not the obj folder.

**Comment by matthewrdev** [comment]
This is expected behaviour.

The obj folder contains various meta-data files that preserve the nuget package cache. A customer requested the ability to delete output folders but keep the local nuget settings so they can use the feature while in offline mode.

Please see https://docs.mfractor.com/utilities/delete-output-folders/#configuring-delete-output-folders

**Comment by HobDev** [comment]
OK,I change the configuration to get the desired results.
Thank you
