### ISSUE TITLE
Exclude from link can't add entry to linker.xml

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#265]
When I use the code action 'Exclude {thing} from linking' it will successfully generate the file the first time, but then the next time I try to preserve a file it doesn't make any changes to XML.

![2020-06-29 17 53 39](https://user-images.githubusercontent.com/29908924/85987842-8d990100-ba31-11ea-9759-0daf1d4ac9bf.gif)
VS Mac 8.6.2
MFractor 4.2.3

**Comment by matthewrdev** [comment]
Thanks for flagging this @lachlanwgordon, I've fixed the bug and it will be available in MFractor 4.2.9. 

For some background, this was caused by a few compounding issues. Firstly, the "insert linker entry" logic using the virtual file path rather than the physical file path. And the linker definition syntax tree was not being rebuilt correctly to include the new types.

Again thanks for flagging, a bit of an oversight with this bug!
