### ISSUE TITLE
MFractor Preferences crashing

### ISSUE THREAD

**Issue by geniesoftstudios** [mfractor/mfractor-feedback#268]
When clicking on **MFractor | Preferences**, this essentially crashes Visual Studio for Mac. 
I am running MFractor 4.2.7 and Visual Studio for Mac 8.6.5 (Build 23)

**Comment by matthewrdev** [comment]
@geniesoftstudios Can you please attach your log files for the session that crashed? Instructions on getting log files are here: https://docs.mfractor.com/support/#visual-studio-mac

**Comment by geniesoftstudios** [comment]
Log files attached as requested. 
[Ide.2020-07-06__18-26-57.log](https://github.com/mfractor/mfractor-feedback/files/4877783/Ide.2020-07-06__18-26-57.log)
[Ide.2020-07-06__18-27-16.log](https://github.com/mfractor/mfractor-feedback/files/4877784/Ide.2020-07-06__18-27-16.log)
[Ide.2020-07-06__18-32-36.log](https://github.com/mfractor/mfractor-feedback/files/4877785/Ide.2020-07-06__18-32-36.log)
[Ide.2020-07-06__18-39-42.log](https://github.com/mfractor/mfractor-feedback/files/4877786/Ide.2020-07-06__18-39-42.log)
[Ide.2020-07-06__18-54-18.log](https://github.com/mfractor/mfractor-feedback/files/4877787/Ide.2020-07-06__18-54-18.log)

**Comment by ravero** [comment]
I can confirm this is happening here to, same version of VS and MFractor, but it only happens when you invoke Preferences from the MFractor top menu **on the Start Window**. It didn't happen when a project is open.

@geniesoftstudios as a workaround you can open the Visual Studio preferences (`Command + ,`) and navigate to the MFractor preferences pane until we analyse and fix.

**Comment by matthewrdev** [comment]
@geniesoftstudios @ravero I've fixed this and it will be available in the next release (4.2.8).
